# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/USER/Downloads/Nano_basic_nim/Nano_basic_nim.cache/wt [current_project]
set_property parent.project_path C:/Users/USER/Downloads/Nano_basic_nim/Nano_basic_nim.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo c:/Users/USER/Downloads/Nano_basic_nim/Nano_basic_nim.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/USER/Downloads/Nano_basic_nim/src/Package Files/BusDefinitions.vhd}
  C:/Users/USER/Downloads/Nano_basic_nim/src/Add_Sub_4.vhd
  C:/Users/USER/Downloads/Nano_basic_nim/src/Address_Selector.vhd
  C:/Users/USER/Downloads/Nano_basic_nim/src/imports/Decoder_2_to_4.vhd
  C:/Users/USER/Downloads/Nano_basic_nim/src/imports/Decoder_3_to_8.vhd
  C:/Users/USER/Downloads/Nano_basic_nim/src/imports/FA.vhd
  C:/Users/USER/Downloads/Nano_basic_nim/src/imports/HA.vhd
  {C:/Users/USER/Downloads/Nano_basic_nim/src/Package Files/constants.vhd}
  C:/Users/USER/Downloads/Nano_basic_nim/src/Instruction_Decoder.vhd
  C:/Users/USER/Downloads/Nano_basic_nim/src/LUT_16_7.vhd
  C:/Users/USER/Downloads/Nano_basic_nim/src/Load_Selector.vhd
  C:/Users/USER/Downloads/Nano_basic_nim/src/imports/Mux_2way_3bit.vhd
  C:/Users/USER/Downloads/Nano_basic_nim/src/imports/Mux_2way_4bit.vhd
  C:/Users/USER/Downloads/Nano_basic_nim/src/imports/Mux_8way_4bit.vhd
  C:/Users/USER/Downloads/Nano_basic_nim/src/PC_Adder.vhd
  C:/Users/USER/Downloads/Nano_basic_nim/src/Program_Counter.vhd
  C:/Users/USER/Downloads/Nano_basic_nim/src/Program_ROM.vhd
  C:/Users/USER/Downloads/Nano_basic_nim/src/imports/RCA_3.vhd
  C:/Users/USER/Downloads/Nano_basic_nim/src/imports/RCA_4.vhd
  C:/Users/USER/Downloads/Nano_basic_nim/src/imports/Reg.vhd
  C:/Users/USER/Downloads/Nano_basic_nim/src/RegisterData_Multiplexer.vhd
  C:/Users/USER/Downloads/Nano_basic_nim/src/Register_Bank.vhd
  C:/Users/USER/Downloads/Nano_basic_nim/src/Slow_Clk.vhd
  C:/Users/USER/Downloads/Nano_basic_nim/src/imports/reg_3bit.vhd
  C:/Users/USER/Downloads/Nano_basic_nim/src/NanoProcessor.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/USER/Downloads/Nano_basic_nim/src/Nanoprocessor_Const.xdc
set_property used_in_implementation false [get_files C:/Users/USER/Downloads/Nano_basic_nim/src/Nanoprocessor_Const.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top NanoProcessor -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef NanoProcessor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file NanoProcessor_utilization_synth.rpt -pb NanoProcessor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
